# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20160701_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('concept', models.CharField(default='Concepto', max_length=100)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Pago')], default='OUT', max_length=3)),
                ('contribution', models.CharField(choices=[('M', 'Me'), ('O', 'Other'), ('B', 'Both')], default='M', max_length=1)),
                ('done', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
    ]
