# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20160701_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('concept', models.CharField(default='Concepto', max_length=100)),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Pago')], default='OUT', max_length=3)),
                ('contribution', models.CharField(choices=[('M', 'Me'), ('O', 'Other'), ('B', 'Both')], default='M', max_length=1)),
                ('done', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('M', 'Mensual'), ('B', 'Bimensual'), ('T', 'Trimestral'), ('A', 'Anual')], default='M', max_length=1)),
                ('next_payment', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-next_payment'],
                'verbose_name': 'Pago regular',
                'verbose_name_plural': 'Pagos regulares',
            },
        ),
    ]
