# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import smartfields.fields
import smartfields.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_regularpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('icon', smartfields.fields.ImageField(upload_to='media/category_icon/')),
                ('icon_mini', smartfields.fields.ImageField(upload_to='media/category_icon_mini')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
            bases=(smartfields.models.SmartfieldsModelMixin, models.Model),
        ),
    ]
