# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations
import smartfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_movement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=smartfields.fields.ImageField(upload_to='category_icon/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_mini',
            field=smartfields.fields.ImageField(upload_to='category_icon_mini/'),
        ),
    ]
